BEGIN TRANSACTION;

INSERT INTO `mnl_accident_pipeline_dataset.dim_vehicle` (vehicle_type, vehicle_group, suggested_from, is_verified)
VALUES
  ('TRUCK', 'COMMERCIAL', 'NONE', TRUE),
  ('ELF TRUCK', 'COMMERCIAL', 'NONE', TRUE),
  ('BUS', 'PUBLIC', 'NONE', TRUE),
  ('AMBULANCE', 'PUBLIC', 'NONE', TRUE),
  ('L300', 'COMMERCIAL', 'NONE', TRUE),
  ('DELIVERY VAN', 'COMMERCIAL', 'NONE', TRUE),
  ('TRAILER', 'COMMERCIAL', 'NONE', TRUE),
  ('16-WHEELER TRUCK', 'COMMERCIAL', 'NONE', TRUE),
  ('10-WHEELER TRUCK', 'COMMERCIAL', 'NONE', TRUE),
  ('DUMP TRUCK', 'COMMERCIAL', 'NONE', TRUE),
  ('PEDESTRIAN', 'NON-VEHICLE', 'NONE', TRUE),
  ('AUV', 'PRIVATE', 'NONE', TRUE),
  ('CAR', 'PRIVATE', 'NONE', TRUE),
  ('SUV', 'PRIVATE', 'NONE', TRUE),
  ('PICK-UP', 'PRIVATE', 'NONE', TRUE),
  ('VAN', 'PRIVATE', 'NONE', TRUE),
  ('CLOSED VAN', 'COMMERCIAL', 'NONE', TRUE),
  ('MC', 'PRIVATE', 'NONE', TRUE),
  ('INNOVA', 'PRIVATE', 'NONE', TRUE),
  ('MOTORCYCLE', 'PRIVATE', 'NONE', TRUE),
  ('HI-ACE VAN', 'PRIVATE', 'NONE', TRUE),
  ('UV EXPRESS', 'PUBLIC', 'NONE', TRUE),
  ('PUJ', 'PUBLIC', 'NONE', TRUE),
  ('TAXI', 'PUBLIC', 'NONE', TRUE),
  ('MINI BUS', 'PUBLIC', 'NONE', TRUE),
  ('UV', 'PUBLIC', 'NONE', TRUE),
  ('MODERN JEEPNEY', 'PUBLIC', 'NONE', TRUE),
  ('E-JEEP', 'PUBLIC', 'NONE', TRUE);

COMMIT TRANSACTION;